### ISSUE TITLE
assets not working in rails 4

### ISSUE THREAD

**Issue by ardianys** [subosito/audiojs-rails#3]
Halo Lif,
assets seems not working on my rails 4 app 

/assets/audiojs-3146e8da3fef83b1a7f267969ac3fa1f.swf?playerInstance=audiojs.instances[%27audiojs4%27]&datetime=1409035920325.86

-> not found

**Comment by subosito** [comment]
Thanks M,

Fixed in 95391494c672a6383502420755cd62c10bd1e314. You can simply use updated version `v0.1.4`. By `gem update audiojs` or by specifying the version in your `Gemfile`.

**Comment by ardianys** [comment]
Sip

**Comment by ardianys** [comment]
tak rake assets:precompile kok gak ada file yg ditulis ulang ya lif ? sama masih error yg di web.
![screenshot from 2014-08-27 16 59 07](https://cloud.githubusercontent.com/assets/196382/4058094/d5045470-2dd0-11e4-8283-58abfec4336f.png)

**Comment by subosito** [comment]
Ada `Gemfile` ato `Gemfile.lock`? dan gist buat output rake assets precompile m?

**Comment by ardianys** [comment]
ok Gemfile.lock belum tak remove dulu, sudah ok sekarang. sip.

2014-08-27 17:11 GMT+07:00 Alif Rachmawadi notifications@github.com:

> Reopened #3 https://github.com/subosito/audiojs/issues/3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/subosito/audiojs/issues/3#event-157782007.

## 

## Ardian Yuli Setyanto

P : 085 643 077 390
S, FB, T : ardianys
W : ardianys.com ilmoe.com http://www.ilmoe.com/

**Comment by subosito** [comment]
Sip
