### ISSUE TITLE
Renaming repo audiojs-rails

### ISSUE THREAD

**Issue by brendon** [subosito/audiojs-rails#4]
Hi there :) Would you consider renaming your repo and gem to `audiojs-rails`? It seems to be the standard notation for Rails Asset Pipeline versions of javascript libraries and should make yours easier to find. I initially thought this was the actual audiojs javascript library.

**Comment by stereodenis** [comment]
:+1:

**Comment by subosito** [comment]
Yup, it's now exist on https://rubygems.org/gems/audiojs-rails and as you can see this repo url has been changed as well :). Thanks guys :+1:.

**Comment by brendon** [comment]
Woohoo! Thanks :D
